// Generated by CoffeeScript 1.7.1
(function() {
  var app, defaultCorsHeaders, express, fs;

  fs = require('fs');

  express = require('express');

  app = express();

  console.log(__dirname);

  app.use(express["static"](__dirname + '/client'));

  defaultCorsHeaders = {
    "access-control-allow-origin": "*",
    "access-control-allow-methods": "GET, POST, PUT, DELETE, OPTIONS",
    "access-control-allow-headers": "content-type, accept",
    "access-control-max-age": 10,
    "Content-Type": "text/plain"
  };

  app.use(function(req, res, next) {
    console.log("" + req.method + " " + req.url);
    res.set(defaultCorsHeaders);
    return next();
  });

  app.get('/', function(req, res) {
    return res.sendfile('index.html');
  });

  app.get('/classes/messages', function(req, res) {
    return fs.readFile(__dirname + '/messages.json', function(err, data) {
      if (err) {
        throw err;
      }
      return res.send(data);
    });
  });

  app.post('/classes/messages', function(req, res) {
    return req.on('data', function(data) {
      data = JSON.parse(data);
      data['createdAt'] = new Date;
      return fs.readFile(__dirname + '/messages.json', function(err, storedData) {
        if (err) {
          throw err;
        }
        storedData = JSON.parse(storedData);
        data['objectId'] = storedData.results.length;
        storedData.results.push(data);
        fs.writeFile(__dirname + '/messages.json', JSON.stringify(storedData), function(err) {
          if (err) {
            throw err;
          }
        });
        return res.send(JSON.stringify({
          objectId: data['objectId'],
          createdAt: data['createdAt']
        }));
      });
    });
  });

  app.use('/*', function(req, res) {
    res.status(404);
    return res.send();
  });

  app.listen(3000);

}).call(this);
